# Generated by Django 5.0.6 on 2024-06-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                ("starting_station", models.CharField(max_length=100)),
                ("destination_station", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("station_id", models.AutoField(primary_key=True, serialize=False)),
                ("station_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.route"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pnr_no", models.CharField(max_length=15, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateTimeField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ticket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                ("train_no", models.AutoField(primary_key=True, serialize=False)),
                ("train_name", models.CharField(max_length=100)),
                ("available_seats", models.IntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.schedule"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.train"
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coach_no", models.CharField(max_length=10)),
                ("seat_no", models.CharField(max_length=10)),
                ("is_filled", models.BooleanField()),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.train"
                    ),
                ),
            ],
            options={
                "unique_together": {("train", "coach_no", "seat_no")},
            },
        ),
        migrations.CreateModel(
            name="Halt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.station"
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.train"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("station", "train", "arrival_time", "departure_time")
                },
            },
        ),
    ]
