# Generated by Django 5.0.6 on 2024-06-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="destination_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_routes",
                to="api.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="starting_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_routes",
                to="api.station",
            ),
        ),
    ]
