# Generated by Django 5.0.6 on 2024-06-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_schedule_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="route",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.route"
            ),
            preserve_default=False,
        ),
    ]
